services:
  mesa:
    build:
      context: ./mesa
    container_name: mesa_app
    ports:
      - "8521:8521"
    volumes:
      - ./mesa/scripts:/app/scripts
      - ./mesa/data:/app/data
    networks:
      - abm-net

  sumo-server:
    build:
      context: ./sumo-traci/sumo
    container_name: sumo-server
    ports:
      - "8813:8813"
    environment:
      - SUMO_HOME=/usr/share/sumo
    command: >
      sumo --remote-port 8813
           -c /sim/config.sumocfg
           --start
           --num-clients 1
    volumes:
      - ./sumo-traci/sumo:/sim
    networks:
      - abm-net
    healthcheck:
      test: ["CMD-SHELL", "netstat -tuln | grep 8813 || exit 1"]
      interval: 2s
      timeout: 5s
      retries: 10

  traci-client:
    build:
      context: ./sumo-traci/controller
    container_name: traci-client
    depends_on:
      sumo-server:
        condition: service_healthy
    environment:
      - SUMO_PORT=8813
      - SUMO_HOST=sumo-server
    networks:
      - abm-net

networks:
  abm-net:
    driver: bridge