services:
  sumo-server:
    build:
      context: ./sumo-traci/sumo
    container_name: sumo-server
    ports:
      - "8813:8813"
    environment:
      - SUMO_HOME=/usr/share/sumo
    command: >
      sumo --remote-port 8813
           -c /sim/config.sumocfg
           --start
    volumes:
      - ./sumo-traci/sumo:/sim
    networks:
      - abm-net
    healthcheck:
      test: ["CMD-SHELL", "netstat -tuln | grep 8813 || exit 1"]
      interval: 2s
      timeout: 5s
      retries: 10
    restart: unless-stopped  # ← NUEVO: Reinicia automáticamente si se cae

  mesa-simulation:
    build:
      context: ./mesa
    container_name: mesa-simulation
    ports:
      - "8521:8521"
    depends_on:
      sumo-server:
        condition: service_healthy
    environment:
      - SUMO_HOST=sumo-server
      - SUMO_PORT=8813
      - N_AGENTS=50
    volumes:
      - ./mesa/scripts:/app/scripts
      - ./mesa/data:/app/data
      - ./results:/app/results
    networks:
      - abm-net

networks:
  abm-net:
    driver: bridge